#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_name=$1
server_ip=$2
username=$3
ssh_private_key_path=$4

scp -o StrictHostKeyChecking=no -i "$ssh_private_key_path" "$file_name" "$username@$server_ip:~/"