#!/usr/bin/env bash
# installing Nginx web server on our web-01 server and
# configures a new Ubuntu machine.

apt update -y
sudo apt upgrade -y
apt install nginx -y
echo "Hello World!" | tee /var/www/html/index.html
service nginx restart
