#!/usr/bin/env bash
# installing Nginx web server on our web-01 server and
# configures a new Ubuntu machine.

sudo apt update -y
sudo apt install -y nginx
sudo service nginx restart
echo "Hello World!" | tee /var/www/html/index.html
sudo sed -i "s|server_name _;|server_name _;\n\trewrite ^/redirect_me https://github.com/sitiabdulaziz11 permanent;|" /etc/nginx/sites-available/default
service nginx restart
