#!/usr/bin/env bash
# installing Nginx web server on our web-01 server and
# configures a new Ubuntu machine.

apt update -y
apt install -y nginx
server {
    listen 80;
    root /var/www/html;
    index index.html;
}
echo "Hello World!" | tee /var/www/html/index.html
service nginx restart