#!/usr/bin/env bash
#  configure web-02 to be identical to web-01,add a custom Nginx response header.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello world' > /var/www/html/index.html
sed -i '/listen 80 default_server;/a add_header X-Served-By $(hostname);' /etc/nginx/sites-available/default
service nginx start
