#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and display bad luck for 4th and
# good luck for 8th.

i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
