#!/usr/bin/env bash
# Bash script that configures Nginx is running as the nginx user and
# nginx must be listening on all active IPs on port 8080.

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
