#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the
# private key ~/.ssh/school with the user ubuntu.

server_ip=34.224.62.139
ssh -i ~/.ssh/school ubuntu@34.224.62.139
